networks:
  dev:

services:
  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    networks:
      - dev

  frontend:
    build:
      context: ./front
    ports:
      - "80:80"
    networks:
      - dev
